services:
  db:
    image: postgres:15-alpine
    environment:
        - POSTGRES_USER=repository1
        - POSTGRES_PASSWORD=lasthero2028
        - POSTGRES_DB=backend_lasthero1
    ports:
      - "5432:5432"
